Repository soroksorokk/soroksorokk_front, pull requests merged in 2023-06, with the labels that each got.

#9 UI / main page and Login, SignUp page
  package.json
  src/App.css
  src/App.tsx
  src/UI/Button.tsx
  src/UI/MainLayout.tsx
  src/UI/MainPostListBox.tsx
  src/UI/Modal.tsx
  src/UI/ModalBackground.tsx
  src/UI/PostDetailPage.tsx
  src/assets/AgreeSign.svg
  src/assets/closeBtn.svg
  src/assets/githubIcon.svg
  src/assets/googleIcon.svg
  src/assets/homeIcon.svg
  src/assets/logo.svg
  src/assets/musicIcon.svg
  src/assets/react.svg
  src/assets/scrapIcon.svg
  src/assets/writeBtn.svg
  src/components/Modal/AlertModal.tsx
  src/components/Modal/ConfirmModal.tsx
  src/components/Modal/GlobalModal.tsx
  src/components/Modal/LoginModal.tsx
  src/components/Modal/SignUpModal.tsx
  src/components/Modal/TermsOfUse.tsx
  src/components/mainPage/Header.tsx
  src/components/mainPage/PostCard.tsx
  src/components/mainPage/PostCardBox.tsx
  src/components/mainPage/PostListHeader.tsx
  src/components/mainPage/PostListNav.tsx
  src/components/mainPage/Toggle.tsx
  src/components/postCard.tsx
  src/hook/useCreate.tsx
  src/hook/useModal.tsx
  src/index.css
  src/main.tsx
  src/router/Login.tsx
  src/router/NewPostPage.tsx
  src/store/isDetailPostOpenState.tsx
  src/store/isNewPostState.tsx
  src/store/modalState.tsx
  src/store/state.tsx
  src/type/custom.d.ts
  src/type/type.tsx
  src/utils/utils.tsx
  tailwind.config.js
  tsconfig.json
  vite.config.ts
Labels: enhancement

#10 UI/profile
  src/components/Profile.tsx
  src/index.css
Labels: design

#11 UI/comment
  public/images/sample/downArrow.svg
  public/images/sample/soondoo.jpeg
  public/images/sample/thumbsUp.svg
  public/images/sample/upArrow.svg
  src/components/Comment.tsx
  src/components/CommentList.tsx
  src/components/ReplyComment.tsx
  tailwind.config.js
Labels: design

#14 UI/detailpage
  public/images/sample/arrow-left.svg
  public/images/sample/play_icon.svg
  src/UI/Button.tsx
  src/UI/MainPostListBox.tsx
  src/UI/Subtitle.tsx
  src/components/post/PostItem.tsx
  src/index.css
Labels: enhancement, design

#15 UI/post list
  public/assets/arrow-left.svg
  public/assets/closeBtn.svg
  public/assets/downArrow.svg
  public/assets/play_icon.svg
  public/assets/soondoo.jpeg
  public/assets/thumbsUp.svg
  public/assets/upArrow.svg
  public/vite.svg
  src/App.tsx
  src/UI/MainPostListBox.tsx
  src/UI/PostDetailPage.tsx
  src/components/Comment.tsx
  src/components/Follow.tsx
  src/components/Modal/LoginModal.tsx
  src/components/Modal/SignUpModal.tsx
  src/components/Profile.tsx
  src/components/ReplyComment.tsx
  src/components/mainPage/Header.tsx
  src/components/mainPage/PostCard.tsx
  src/components/mainPage/PostCardBox.tsx
  src/components/mainPage/PostListHeader.tsx
  src/components/mainPage/PostListNav.tsx
  src/components/mainPage/Toggle.tsx
  src/components/post/PostItem.tsx
  src/index.css
  tailwind.config.js
Labels: enhancement, design
